// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/copy-trading/CopyTrading.tsx": () => import("../components/mockups/copy-trading/CopyTrading.tsx"),
  "./components/mockups/copy-trading/CopyTradingHistory.tsx": () => import("../components/mockups/copy-trading/CopyTradingHistory.tsx"),
  "./components/mockups/copy-trading/CopyTradingSignals.tsx": () => import("../components/mockups/copy-trading/CopyTradingSignals.tsx"),
  "./components/mockups/copy-trading/CopyTradingStrategy.tsx": () => import("../components/mockups/copy-trading/CopyTradingStrategy.tsx"),
  "./components/mockups/rune-glass/Dashboard.tsx": () => import("../components/mockups/rune-glass/Dashboard.tsx"),
  "./components/mockups/rune-glass/Hyperliquid.tsx": () => import("../components/mockups/rune-glass/Hyperliquid.tsx"),
  "./components/mockups/rune-glass/Profile.tsx": () => import("../components/mockups/rune-glass/Profile.tsx"),
  "./components/mockups/rune-glass/Vault.tsx": () => import("../components/mockups/rune-glass/Vault.tsx"),
  "./components/mockups/trade/TradeMarkets.tsx": () => import("../components/mockups/trade/TradeMarkets.tsx")
};
